lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
#theme: minima
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
- jekyll-feed
title: rssh notes
description: Random notes about programming
author: Ruslan Shevchenko

